Utility to convert QoS ids and policies to string
eProsima/dev-utils pull request #118
Opened 2024-06-17 09:05 UTC by Tempate

This version includes `qos_policy_id_to_string` to convert a `QosPolicyId_t` to string and ` qos_policy_mask_to_string` to convert a `PolicyMask` to string.

2024-06-17 14:24 UTC, Tempate commented
@mergifyio backport 0.x

2024-07-02 12:37 UTC, LuciaEchevarria99 requested changes

2024-07-02 12:37 UTC, LuciaEchevarria99 commented on cpp_utils/src/cpp/qos/qos_utils.cpp
> +    }
I prefer not to delete the initial ' ,' from the string. While there's no perfect solution, one approach is to add a parameter to track whether the `QosPolicy` is the first in the sequence.

2024-07-02 12:37 UTC, LuciaEchevarria99 commented on cpp_utils/test/unittest/qos/qos_utils_test.cpp
> +        ASSERT_EQ(id_str, id_str_expected);
Try to parametrize this test, you are writing the same steps to test all `QosPolicyId_t`, why not creating a `std::map<uint32_t, std::string>` (with every `QosPolicyId_t` and its corresponding `std::string`) and iterating through it?

2024-07-02 13:31 UTC, LuciaEchevarria99 approved these changes
LGTM

2024-07-02 14:02 UTC, merged