Utility to convert a string (e.g. 100MB) to a number of bytes
eProsima/dev-utils pull request #96
Opened 2024-02-19 15:27 UTC by Tempate

The format is: any floating number followed by B, KB, MB, GB, TB, PB (case insensitive). The measure unit can also be KiB, MiB, GiB, TiB, PiB (case insensitive).

2024-02-19 18:40 UTC, EduPonz requested changes

2024-02-19 18:40 UTC, EduPonz commented on cpp_utils/src/cpp/utils.cpp
> +unsigned long long to_bytes(const std::string& input)
I'd suggest using explicit size types, in this case `uint64_t`

2024-02-19 18:40 UTC, EduPonz commented on cpp_utils/src/cpp/utils.cpp
> +    const unsigned long long bytes = number * magnitude;
This could overflow, I'd add a check to prevent it. For example what if the input it `9999999999PiB`

2024-02-20 13:17 UTC, EduPonz requested changes

2024-02-20 13:17 UTC, EduPonz commented on cpp_utils/src/cpp/utils.cpp
> +std::uint64_t to_bytes(
Include cstdint

2024-02-20 13:17 UTC, EduPonz commented on cpp_utils/src/cpp/utils.cpp
> +    const std::uint64_t bytes = number * magnitude;
There is a loss of precision here as number being a double, the cast to `uint64_t` will be an approximate of the real input, although I don't know if there is something we can do about it, given that there is no `std::stoui64` 🥲. In that case, I think this should be:
```suggestion
    // Explicit cast to uint64_t is safe here as the number has already been checked to fit.
    // Furthermore, the product is also safe as the possible overflown has also been checked before
    const std::uint64_t bytes = static_cast<std::uint64_t>(number) * magnitude;
```

2024-02-20 14:48 UTC, EduPonz approved these changes

2024-02-23 11:44 UTC, EduPonz submitted a review, later dismissed

2024-03-04 10:16 UTC, LuciaEchevarria99 requested changes

2024-03-07 10:20 UTC, LuciaEchevarria99 submitted a review, later dismissed

2024-03-07 11:21 UTC, LuciaEchevarria99 approved these changes
LGTM

2024-03-07 11:22 UTC, merged